site_name: Company X Docs Site
theme:
  name: material

markdown_extensions:
  - toc:
      permalink: True

# a list of mkdocs plugins: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#site-management
plugins:
  - multirepo: # https://github.com/jdoiro3/mkdocs-multirepo-plugin - bring multiple repos into one doc site
      cleanup: true
      repos:
        - section: Backend
          import_url: 'https://github.com/pavlabs-mkdocs-showcase/backend-service'
        - section: Backend
          import_url: 'https://github.com/pavlabs-mkdocs-showcase/frontend-service'
